Update Jenkinsfile2

diff --git a/Jenkinsfile2 b/Jenkinsfile2
--- a/Jenkinsfile2
+++ b/Jenkinsfile2
@@ -1,70 +1,69 @@
 pipeline {
     agent any
     
+    environment {
+        APP_DIR = "${WORKSPACE}/app-web"
+    }
+
     stages {
-        stage('Create  directory for the WEB Application')        
-       {
+        stage('Create directory for the WEB Application') {
             steps {
-                //First, drop the directory if exists
-                sh 'rm -rf /home/jenkins/app-web'
-                //Create the directory
-                sh 'mkdir /home/jenkins/app-web'               
+                echo "Preparing directory: ${APP_DIR}"
+                sh "rm -rf ${APP_DIR} && mkdir -p ${APP_DIR}"
             }
         }
-        stage('Drop the containers'){   
-            failFast true
-            parallel{ 
-                stage('Drop apache container'){
+        
+        stage('Drop the containers') {
+            parallel {
+                failFast true
+                stage('Drop Apache container') {
                     steps {
-                        echo 'droping the Apache container...'
-                        sh 'ocker rm -f app-web-apache'
+                        echo 'Dropping the Apache container...'
+                        sh 'docker rm -f app-web-apache || true'
                     }
                 }
-                stage('Drop Nginx Container'){
-                    steps{
-                        echo 'droping the Nginx container...'
-                        sh 'docker rm -f app-web-nginx'
+                stage('Drop Nginx container') {
+                    steps {
+                        echo 'Dropping the Nginx container...'
+                        sh 'docker rm -f app-web-nginx || true'
                     }
                 }           
             }
         }
-        //Creating the containers in Parallel
+        
         stage('Create the containers in Parallel') {
-            parallel{
-                stage('Create the Apache container')
-                {           
+            parallel {
+                stage('Create the Apache container') {           
                     steps {
-                    echo 'Creating the Apache Container...'
-                    sh 'docker run -dit --name app-web-apache -p 9100:80  -v /home/jenkins/app-web:/usr/local/apache2/htdocs/ httpd'
+                        echo 'Creating the Apache Container...'
+                        sh "docker run -dit --name app-web-apache -p 9100:80 -v ${APP_DIR}:/usr/local/apache2/htdocs/ httpd"
                     }
                 }
                 stage('Create the Nginx container') {
-                   steps {
-                   echo 'Creating the Apache container...'
-                   sh 'docker run -dit --name app-web-nginx -p 9200:80  -v /home/jenkins/app-web:/usr/share/nginx/html nginx'         
-                   }
+                    steps {
+                        echo 'Creating the Nginx Container...'
+                        sh "docker run -dit --name app-web-nginx -p 9200:80 -v ${APP_DIR}:/usr/share/nginx/html nginx"
+                    }
                 }       
             }   
         }
-        //Copy the application   
+        
         stage('Copy the web application to the container directory') {
             steps {
-                echo 'Copying web application...'             
-                sh 'cp -r web/* /home/jenkins/app-web'
+                echo 'Copying web application...'
+                sh "[ -d web ] && cp -r web/* ${APP_DIR} || echo 'No web directory found, skipping copy.'"
             }
         }
     }
 
     post {              
         success {
-        // One or more steps need to be included within each condition's block.
-          echo 'The deployment in Nginx and Apache has worked'
-          archiveArtifacts allowEmptyArchive: true, artifacts: 'web/*', followSymlinks: false
-          cleanWs()         
-       }
-       failure {
-        // One or more steps need to be included within each condition's block.
-        echo 'An error has ocurred in the deploy'       
-       }
+            echo 'The deployment in Nginx and Apache has worked'
+            archiveArtifacts allowEmptyArchive: true, artifacts: 'web/*', followSymlinks: false
+            cleanWs()         
+        }
+        failure {
+            echo 'An error has occurred in the deploy'
+        }
     }
 }
